# Generated by Django 5.0.3 on 2024-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_version_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер версии'),
        ),
    ]
