# Generated by Django 5.0.3 on 2024-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_version_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.PositiveIntegerField(verbose_name='Номер версии'),
        ),
    ]
