# Generated by Django 5.0.3 on 2024-04-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('can_edit_is_published', 'Can edit is_published'), ('can_edit_category', 'Can edit category'), ('can_edit_description', 'Can edit description')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
